* 2019
** 2019-01 一月
*** 2019-01-07 星期一
**** 工具流折腾总结
Entered on [2019-01-07 一 08:36]

工具流的配置时间远远超过计划，周末两天计划做一些实际的事情，但是现在是周一的早上，刚刚结束对输入法的配置。踩了几个坑。发现几个问题：

1. 如果目标不明确，或者说需求不清晰的时候，进度很难掌握，因为发现一些可有可无的东西的时候，没有标准判断是否舍弃还是继续追下去。
2. 执行过程中对变量的控制非常重要，原则是，确定最小需求，跑通流程后优化。这点很重要。
3. 调研 － 分析需求 － 给出详细需求 － 做 － 控制变量 －收工。
**** work flow
Entered on [2019-01-07 一 08:53]

org-capture  >  org-refile

每周整理下所有的节点
*** 2019-01-09 Wednesday
**** 关于趋势和真金的思考
[2019-01-09 Wed 20:18]
看论坛关于 emacs 与 intellij 的讨论有感。
emacs 有他的魅力，但是门槛过高，发展趋势不符合主流，所以它终归只是小众的东西。
现代化的 ide 瞄准 web 编程的痛点，门槛较低，现在发展的红红火火。
喜欢 emacs 的一部分人长时间守着所谓的真金走不出来，十分可惜。

趋势不一定是好的，不一定是对的，和真金是两回事情。
你觉得你发现了一块被大家的金子，然后守着它，觉得全世界终会注意到它。不对。
引导很重要，也是根本动力。
趋势都是盲目的，因为人群总是盲目的，短视的，符合直觉的。除非你有方法或者有影响力让大家看到这块金子。
这个区别很重要，涉及到事物的价值成长的问题，需要个人的 push 能力。
所以，这两个点，趋势和真金都需要自己的思考和观察，区分两者。
我对自己的定位是可以提出问题和解决问题的实用主义，至少目前是。
实用主义就要求个人要时刻保持清醒，对待真金要会欣赏，对待趋势要学会引导。
就像我 emacs 和 intellij 都会使用，前者用于处理零碎的需求，本着欣赏和尝试的目的，后者为了工作和效率。
我会尝试在欣赏真金和顺应趋势之间找到平衡.
**** 解藕的重要性
[2019-01-09 Wed 20:48]
一定要把事情尽可能解藕，不要形成太多 key point，这样会严重影响推进效率。
先推进，再优化
*** 2019-01-10 Thursday
**** test clock
[2019-01-10 Thu 15:09]
tex  t
*** 2019-01-19 Saturday
**** 环境终于配置完成了
[2019-01-19 Sat 00:05]
前前后后折腾了一圈，从 emacs 折腾到 docker，到 ubuntu，到 orgmode， 到 beorg，到 spacemacs，到 i3wm，到 archlinux，到 manjaro，到 vmware fusion，到 chunkwm，最后还是回到了 mac，使用了 chunkwm，后续功能再慢慢补，基本功能闭环了，可以松口气了。明天就回家了，希望这次没有什么幺蛾子。
**** 跟组长聊了下近况
需要改变下工作方式了，需要主动起来，自己发现问题，并解决问题，这两个都很重要。
[2019-02-03 Sun 00:20]
*** 2019-01-23 Wednesday
**** chunkwm 配置
折腾才能真的学会，因为训练了熟练度
折腾的多了，会发现结果不重要，过程最重要，因为折腾的过程中，自己反复确认了真正的需求
[2019-01-23 Wed 17:19]
*** 2019-01-24 Thursday
**** 又试了下 manjaro
[2019-01-24 Thu 08:33]
任何计划都要尽早开始，时间带来的认知复利很容易被忽视，但是这个其实很很重要。
另外，不要理想化。
*** 2019-01-27 Sunday
**** 能够变现的代码
比如一些小工具：格式转换之类的，代下载。
[2019-01-27 Sun 00:32]
**** 动物语言翻译调研
[2019-01-27 Sun 18:54]
** 2019-02 February
*** 2019-02-04 Monday
**** 春节之一：烦

[2019-02-04 Mon 11:29]
*** 2019-02-09 Saturday
**** 春节终于要结束了
人与人之间充满了利益争执
处理好利益争执可能就是管理的艺术吧
感觉还是
[2019-02-09 Sat 09:38]
*** 2019-02-15 Friday
**** DONE myemacs is running                                                    :@coding:@computer:
DEADLINE: <2019-02-16 Sat>
<2019-02-15 Fri>

[2019-02-15 Fri 17:49]
